### ISSUE TITLE
HTTParty SSL certificate error

### ISSUE THREAD

**Issue by noahgibbs** [expectedbehavior/doc_raptor_gem#16]
Recent Ruby started requiring a valid SSL cert by default. Not sure if the problem is on my end or yours, but HTTParty is failing hard when I try to use the DocRaptor API:

```
/Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/noah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/noah/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
	from /Users/noah/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	from /Users/noah/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty.rb:492:in `post'
	from /Users/noah/.rvm/gems/ruby-2.2.1/gems/doc_raptor-0.5.0/lib/doc_raptor.rb:58:in `create'
	from ./html_to_pdf.rb:12:in `block (2 levels) in <main>'
	from ./html_to_pdf.rb:11:in `open'
	from ./html_to_pdf.rb:11:in `block in <main>'
	from ./html_to_pdf.rb:7:in `each'
	from ./html_to_pdf.rb:7:in `<main>'
```

I've tried updating RVM and running "rvm osx-ssl-certs update all", so that doesn't help.

**Comment by janxious** [comment]
@noahgibbs What URL are you trying to contact? Drop in here (or DocRaptor support if it's sensitive).

**Comment by noahgibbs** [comment]
I'm using the DocRaptor.create() call in the doc_raptor gem, version 0.5.0 -- you can see it in the call stack above. So I'm using whatever the default URL is for the create call in doc_raptor.

Reading the code, it looks like that's the /docs URL.

**Comment by janxious** [comment]
Dur. That's obviously the URL. Will look a little more and get back to you.

**Comment by janxious** [comment]
@noahgibbs So I popped open the gem source code, updated the ruby version to 2.2.3, bundled, and then ran `bundle exec ruby examples/docraptor_gem_example.rb` and it did not produce SSL errors. Changes are [here](https://github.com/expectedbehavior/doc_raptor_gem/tree/ssl-issue).

```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

$ bundle list
Gems included by the bundle:
  * addressable (2.3.8)
  * bundler (1.10.6)
  * coderay (1.1.0)
  * crack (0.4.2)
  * doc_raptor (0.5.0)
  * httparty (0.13.5)
  * json (1.8.3)
  * method_source (0.8.2)
  * minitest (5.8.0)
  * multi_xml (0.5.5)
  * pry (0.10.1)
  * rake (10.4.2)
  * safe_yaml (1.0.4)
  * slop (3.6.0)
  * webmock (1.21.0)
```

Could I get you to check out versions of everything on your system?

**Comment by noahgibbs** [comment]
The way I fixed it was to downgrade HTTParty to 0.10.0. Can I ask you to also check w/ most recent HTTParty?

(And yeah, I'll try reinstalling Ruby, doc_raptor, HTTParty, etc. tonight.)

**Comment by noahgibbs** [comment]
Hm. Looks like you checked w/ HTTParty 0.13.5, which is at least quite recent. I should check w/ that. Technically *most* recent is 0.13.7, so maybe it's some kind of recent reversion? I'll check again tonight.

**Comment by janxious** [comment]
I checked with 0.13.7 and that also worked. I am on OSX Yosemite. Let me know if you need me to spin up a VM or something to help out.

Also a little more: https://www.sslshopper.com/ssl-checker.html#hostname=https://docraptor.com

**Comment by panozzaj** [comment]
Ran into the same issue on my machine, with `doc_raptor` at 0.5.0 and Ruby version 2.2.3p173 on RVM. Running the following seems to fix the problem for me:

```
rvm osx-ssl-certs update all
rvm reinstall 2.2.3 --disable-binary
rvm gemset use global
gem install bundler
cd .. ; cd -  # use my project's gemset
bundle install
```

Hope this helps someone!

**Comment by northband** [comment]
@panozzaj thanks for the fix - it worked for a local issue I was having.

**Comment by janxious** [comment]
@noahgibbs closing this since there is a workaround noted. If you run into the problem again, feel free to re-open
