### ISSUE TITLE
Tempfile encoding ascii-8bit

### ISSUE THREAD

**Issue by Yardboy** [expectedbehavior/doc_raptor_gem#6]
I'm getting the following error from line 67 of doc_raptor.rb:

```ruby
"\xE2" from ASCII-8BIT to UTF-8
```

I've discovered that if I change line 65 in doc_raptor.rb from:

```ruby
Tempfile.open("docraptor") do |f|
```

to

```ruby
Tempfile.open("docraptor", :encoding => "ascii-8bit") do |f|
```

...then the problem is solved.

This appears to be related to my Rails app application.rb having the following:

```ruby
config.encoding = "utf-8"
```

This, as I understand it, is the default for Rails 3+. Should I submit a patch with this change?

**Comment by jqr** [comment]
Released version `0.3.3` with your fix from #8.
